export type TeamMember = {
  id: string;
  type: "doctor" | "nurse";
  name: string;
  role: string;
  image: string;
  str: string;
  education: string;
  certifications: string[];
  experience: string;
  bio: string;
  socials: {
    instagram: string;
    linkedin: string;
  };
};

export const teamData: TeamMember[] = [
  // --- DOCTORS (9 Dummy Profiles) ---
  {
    id: "dr-alex",
    type: "doctor",
    name: "dr. Alexander Sterling",
    role: "Licensed Doctor",
    image: "/images/team/001.webp",
    str: "STR-2026-001-XXXX",
    education: "Medical Faculty University",
    certifications: ["ACLS", "HIPERKES"],
    experience: "8+ Years",
    bio: "General practitioner specializing in rapid medical response and comprehensive home care diagnostics.",
    socials: { instagram: "#", linkedin: "#" },
  },
  {
    id: "dr-sarah",
    type: "doctor",
    name: "dr. Sarah Mackenzie",
    role: "Licensed Doctor",
    image: "/images/team/004.webp",
    str: "STR-2026-002-XXXX",
    education: "Health Science University",
    certifications: ["ATLS", "Internal Medicine"],
    experience: "6+ Years",
    bio: "Expert in patient management and chronic disease consultation, focusing on villa-based services.",
    socials: { instagram: "#", linkedin: "#" },
  },
  {
    id: "dr-brian",
    type: "doctor",
    name: "dr. Brian O'Connor",
    role: "Licensed Doctor",
    image: "/images/team/002.webp",
    str: "STR-2026-003-XXXX",
    education: "International Medical School",
    certifications: ["ACLS", "Primary Care"],
    experience: "5+ Years",
    bio: "Dedicated medical professional with a focus on intravenous therapy and recovery ecosystems.",
    socials: { instagram: "#", linkedin: "#" },
  },
  {
    id: "dr-julie",
    type: "doctor",
    name: "dr. Juliana Vallery",
    role: "Licensed Doctor",
    image: "/images/team/005.webp",
    str: "STR-2026-004-XXXX",
    education: "Faculty of Medicine",
    certifications: ["Public Health Master", "ACLS"],
    experience: "7+ Years",
    bio: "Combining clinical excellence with public health expertise for high-standard home care.",
    socials: { instagram: "#", linkedin: "#" },
  },
  {
    id: "dr-adrian",
    type: "doctor",
    name: "dr. Adrian Hartanto",
    role: "Licensed Doctor",
    image: "/images/team/006.webp",
    str: "STR-2026-005-XXXX",
    education: "Metropolitan University",
    certifications: ["ATLS", "Emergency Medicine"],
    experience: "4+ Years",
    bio: "Specializing in emergency stabilization and rapid on-call medical intervention.",
    socials: { instagram: "#", linkedin: "#" },
  },
  {
    id: "dr-clara",
    type: "doctor",
    name: "dr. Clara Anindya",
    role: "Licensed Doctor",
    image: "/images/team/003.webp",
    str: "STR-2026-006-XXXX",
    education: "National Health Institute",
    certifications: ["ACLS", "Pediatric Care"],
    experience: "6+ Years",
    bio: "Focusing on family medicine and pediatric home-visit consultations across Bali.",
    socials: { instagram: "#", linkedin: "#" },
  },
  {
    id: "dr-victor",
    type: "doctor",
    name: "dr. Victor Ibrahim",
    role: "Licensed Doctor",
    image: "/images/team/008.webp",
    str: "STR-2026-007-XXXX",
    education: "Global Medical Center",
    certifications: ["Hyperbaric Medicine", "ACLS"],
    experience: "5+ Years",
    bio: "Expert in travel medicine and recovery for tourists with specific tropical illness needs.",
    socials: { instagram: "#", linkedin: "#" },
  },
  {
    id: "dr-maya",
    type: "doctor",
    name: "dr. Maya Putri",
    role: "Licensed Doctor",
    image: "/images/team/007.webp",
    str: "STR-2026-008-XXXX",
    education: "Regional Health University",
    certifications: ["ACLS", "Dermatology Basic"],
    experience: "4+ Years",
    bio: "General practitioner with interest in skin recovery and IV vitamin therapy.",
    socials: { instagram: "#", linkedin: "#" },
  },
  {
    id: "dr-kevin",
    type: "doctor",
    name: "dr. Kevin Sanjaya",
    role: "Licensed Doctor",
    image: "/images/user.jpeg",
    str: "STR-2026-009-XXXX",
    education: "Sports Medicine Academy",
    certifications: ["ATLS", "Sports Medicine"],
    experience: "7+ Years",
    bio: "Specialized in sports injuries and orthopedic pain management for villa-based recovery.",
    socials: { instagram: "#", linkedin: "#" },
  },

  // --- NURSES (16 Dummy Profiles) ---
  {
    id: "ns-mark",
    type: "nurse",
    name: "Ns. Marcus Thorne",
    role: "Professional Nurse",
    image: "/images/user.jpeg",
    str: "NS-2026-101-XXXX",
    education: "Nursing School Institute",
    certifications: ["BTCLS", "Emergency Nursing"],
    experience: "6+ Years",
    bio: "Highly skilled nurse specializing in IV therapy and Bali Belly recovery.",
    socials: { instagram: "#", linkedin: "#" },
  },
  {
    id: "ns-bella",
    type: "nurse",
    name: "Ns. Bella Swanita",
    role: "Professional Nurse",
    image: "/images/user.jpeg",
    str: "NS-2026-102-XXXX",
    education: "Nursing Science Academy",
    certifications: ["Home Care Specialist"],
    experience: "5+ Years",
    bio: "Expert in nursing care and clinical assistance for post-surgery patients.",
    socials: { instagram: "#", linkedin: "#" },
  },
  {
    id: "ns-rizky",
    type: "nurse",
    name: "Ns. Rizky Ramadhan",
    role: "Professional Nurse",
    image: "/images/user.jpeg",
    str: "NS-2026-103-XXXX",
    education: "Health Polytechnic",
    certifications: ["Emergency First Aid"],
    experience: "4+ Years",
    bio: "Fast-responding nurse with extensive experience in hotel medical call-outs.",
    socials: { instagram: "#", linkedin: "#" },
  },
  {
    id: "ns-linda",
    type: "nurse",
    name: "Ns. Linda Permata",
    role: "Professional Nurse",
    image: "/images/user.jpeg",
    str: "NS-2026-104-XXXX",
    education: "Bina Husada Institute",
    certifications: ["Pediatric Nursing"],
    experience: "5+ Years",
    bio: "Compassionate nurse specializing in infant and child medical monitoring at home.",
    socials: { instagram: "#", linkedin: "#" },
  },
  {
    id: "ns-david",
    type: "nurse",
    name: "Ns. David Setiawan",
    role: "Professional Nurse",
    image: "/images/user.jpeg",
    str: "NS-2026-105-XXXX",
    education: "Nursing Global School",
    certifications: ["BTCLS", "ICU Nursing"],
    experience: "7+ Years",
    bio: "Critical care specialist providing high-level monitoring for complex home cases.",
    socials: { instagram: "#", linkedin: "#" },
  },
  {
    id: "ns-yoga",
    type: "nurse",
    name: "Ns. Yoga Pratama",
    role: "Professional Nurse",
    image: "/images/user.jpeg",
    str: "NS-2026-106-XXXX",
    education: "State Nursing Faculty",
    certifications: ["Wound Care Certified"],
    experience: "6+ Years",
    bio: "Specialist in advanced wound dressing and post-operative recovery care.",
    socials: { instagram: "#", linkedin: "#" },
  },
  {
    id: "ns-rina",
    type: "nurse",
    name: "Ns. Rina Melati",
    role: "Professional Nurse",
    image: "/images/user.jpeg",
    str: "NS-2026-107-XXXX",
    education: "Nursing Wellness Institute",
    certifications: ["BTCLS", "Geriatic Care"],
    experience: "5+ Years",
    bio: "Expert in elderly care and long-term medical management for villa residents.",
    socials: { instagram: "#", linkedin: "#" },
  },
  {
    id: "ns-tony",
    type: "nurse",
    name: "Ns. Tony Wijaya",
    role: "Professional Nurse",
    image: "/images/user.jpeg",
    str: "NS-2026-108-XXXX",
    education: "Health Science Academy",
    certifications: ["BTCLS", "Anesthesia Support"],
    experience: "6+ Years",
    bio: "Assisting in minor surgical procedures and pain management therapy.",
    socials: { instagram: "#", linkedin: "#" },
  },
  {
    id: "ns-anita",
    type: "nurse",
    name: "Ns. Anita Kusuma",
    role: "Professional Nurse",
    image: "/images/user.jpeg",
    str: "NS-2026-109-XXXX",
    education: "National Nursing School",
    certifications: ["BTCLS", "Maternity Care"],
    experience: "5+ Years",
    bio: "Dedicated to maternal health and newborn care assistance in villa settings.",
    socials: { instagram: "#", linkedin: "#" },
  },
  {
    id: "ns-fajar",
    type: "nurse",
    name: "Ns. Fajar Syahputra",
    role: "Professional Nurse",
    image: "/images/user.jpeg",
    str: "NS-2026-110-XXXX",
    education: "Institute of Nursing",
    certifications: ["BTCLS", "Mental Health Nursing"],
    experience: "4+ Years",
    bio: "Providing holistic nursing care with a focus on patient psychological comfort.",
    socials: { instagram: "#", linkedin: "#" },
  },
  {
    id: "ns-michella",
    type: "nurse",
    name: "Ns. Michella Rose",
    role: "Professional Nurse",
    image: "/images/user.jpeg",
    str: "NS-2026-111-XXXX",
    education: "International Health Poltek",
    certifications: ["BTCLS", "Nutrition Support"],
    experience: "5+ Years",
    bio: "Specialized in IV hydration and nutritional recovery for hangover/immunity.",
    socials: { instagram: "#", linkedin: "#" },
  },
  {
    id: "ns-erik",
    type: "nurse",
    name: "Ns. Erik Kurniawan",
    role: "Professional Nurse",
    image: "/images/user.jpeg",
    str: "NS-2026-112-XXXX",
    education: "Nursing Excellence School",
    certifications: ["BTCLS", "Emergency Trauma"],
    experience: "6+ Years",
    bio: "Experienced in trauma response and mobile medical unit coordination.",
    socials: { instagram: "#", linkedin: "#" },
  },
  {
    id: "ns-dian",
    type: "nurse",
    name: "Ns. Dian Sasmita",
    role: "Professional Nurse",
    image: "/images/user.jpeg",
    str: "NS-2026-113-XXXX",
    education: "Metropolitan Nursing",
    certifications: ["BTCLS", "Infection Control"],
    experience: "5+ Years",
    bio: "Focused on clinical safety and high-standard sterilization in home care.",
    socials: { instagram: "#", linkedin: "#" },
  },
  {
    id: "ns-hendra",
    type: "nurse",
    name: "Ns. Hendra Gunawan",
    role: "Professional Nurse",
    image: "/images/user.jpeg",
    str: "NS-2026-114-XXXX",
    education: "Senior Nursing Academy",
    certifications: ["BTCLS", "Renal Care"],
    experience: "7+ Years",
    bio: "Senior nurse with expertise in dialysis assistance and renal monitoring.",
    socials: { instagram: "#", linkedin: "#" },
  },
  {
    id: "ns-widya",
    type: "nurse",
    name: "Ns. Widya Astuti",
    role: "Professional Nurse",
    image: "/images/user.jpeg",
    str: "NS-2026-115-XXXX",
    education: "Nursing Palliative Institute",
    certifications: ["BTCLS", "Palliative Care"],
    experience: "5+ Years",
    bio: "Specializing in compassionate palliative care and family medical support.",
    socials: { instagram: "#", linkedin: "#" },
  },
  {
    id: "ns-bagus",
    type: "nurse",
    name: "Ns. Bagus Dharmawan",
    role: "Professional Nurse",
    image: "/images/user.jpeg",
    str: "NS-2026-116-XXXX",
    education: "Home Care Nursing School",
    certifications: ["BTCLS", "General Home Care"],
    experience: "4+ Years",
    bio: "Providing versatile nursing services for general health check-ups and IV drips.",
    socials: { instagram: "#", linkedin: "#" },
  },
];
