export type TeamMember = {
  id: string;
  type: "doctor" | "nurse";
  name: string;
  role: string;
  image: string;
  str: string;
  education: string;
  certifications: string[];
  experience: string;
  bio: string;
  socials: {
    instagram: string;
    linkedin: string;
  };
};

export const teamData: TeamMember[] = [
  // --- DOCTORS (9 People) ---
  {
    id: "dr-mega",
    type: "doctor",
    name: "dr. Ni Wayan Mega Rajuni",
    role: "Licensed Doctor",
    image: "/images/user.jpeg",
    str: "STR-2026-001-MEGA",
    education: "Universitas Warmadewa",
    certifications: ["ACLS", "HIPERKES"],
    experience: "5+ Years",
    bio: "General practitioner specializing in rapid medical response and comprehensive home care diagnostics.",
    socials: { instagram: "#", linkedin: "#" },
  },
  {
    id: "dr-lorenzo",
    type: "doctor",
    name: "dr. Lorenzo Alexander Pradhana",
    role: "Licensed Doctor",
    image: "/images/user.jpeg",
    str: "STR-2026-002-LOREN",
    education: "Universitas Udayana",
    certifications: ["ATLS", "Internal Medicine"],
    experience: "4+ Years",
    bio: "Expert in patient management and chronic disease consultation, focusing on villa-based services.",
    socials: { instagram: "#", linkedin: "#" },
  },
  {
    id: "dr-wahyu",
    type: "doctor",
    name: "dr. Anak Agung Gede Wahyu P.",
    role: "Licensed Doctor",
    image: "/images/user.jpeg",
    str: "STR-2026-003-WAHYU",
    education: "Universitas Warmadewa",
    certifications: ["ACLS", "Primary Care"],
    experience: "4+ Years",
    bio: "Dedicated medical professional with a focus on intravenous therapy and recovery ecosystems.",
    socials: { instagram: "#", linkedin: "#" },
  },
  {
    id: "dr-cahyadi",
    type: "doctor",
    name: "dr. Cahyadi Surya, MPH",
    role: "Licensed Doctor",
    image: "/images/user.jpeg",
    str: "STR-2026-004-CAHYA",
    education: "Universitas Udayana",
    certifications: ["Public Health Master", "ACLS"],
    experience: "6+ Years",
    bio: "Combining clinical excellence with public health expertise for high-standard home care.",
    socials: { instagram: "#", linkedin: "#" },
  },
  {
    id: "dr-putra",
    type: "doctor",
    name: "dr. I Made Aditya Putra",
    role: "Licensed Doctor",
    image: "/images/user.jpeg",
    str: "STR-2026-005-ADIT",
    education: "Universitas Udayana",
    certifications: ["ATLS", "Emergency Medicine"],
    experience: "3+ Years",
    bio: "Specializing in emergency stabilization and rapid on-call medical intervention.",
    socials: { instagram: "#", linkedin: "#" },
  },
  {
    id: "dr-saraswati",
    type: "doctor",
    name: "dr. Ni Putu Ayu Saraswati",
    role: "Licensed Doctor",
    image: "/images/user.jpeg",
    str: "STR-2026-006-SARAS",
    education: "Universitas Warmadewa",
    certifications: ["ACLS", "Pediatric Care"],
    experience: "5+ Years",
    bio: "Focusing on family medicine and pediatric home-visit consultations across Bali.",
    socials: { instagram: "#", linkedin: "#" },
  },
  {
    id: "dr-wiguna",
    type: "doctor",
    name: "dr. Gede Bagus Wiguna",
    role: "Licensed Doctor",
    image: "/images/user.jpeg",
    str: "STR-2026-007-BAGUS",
    education: "Universitas Udayana",
    certifications: ["Hyperbaric Medicine", "ACLS"],
    experience: "4+ Years",
    bio: "Expert in travel medicine and recovery for tourists with specific tropical illness needs.",
    socials: { instagram: "#", linkedin: "#" },
  },
  {
    id: "dr-dewi",
    type: "doctor",
    name: "dr. Kadek Shanti Dewi",
    role: "Licensed Doctor",
    image: "/images/user.jpeg",
    str: "STR-2026-008-SHANTI",
    education: "Universitas Warmadewa",
    certifications: ["ACLS", "Dermatology Basic"],
    experience: "3+ Years",
    bio: "General practitioner with interest in skin recovery and IV vitamin therapy.",
    socials: { instagram: "#", linkedin: "#" },
  },
  {
    id: "dr-setiawan",
    type: "doctor",
    name: "dr. Agus Setiawan",
    role: "Licensed Doctor",
    image: "/images/user.jpeg",
    str: "STR-2026-009-AGUS",
    education: "Universitas Udayana",
    certifications: ["ATLS", "Sports Medicine"],
    experience: "6+ Years",
    bio: "Specialized in sports injuries and orthopedic pain management for villa-based recovery.",
    socials: { instagram: "#", linkedin: "#" },
  },

  // --- NURSES (16 People) ---
  {
    id: "loisa",
    type: "nurse",
    name: "Loisa Lakamai",
    role: "Professional Nurse",
    image: "/images/user.jpeg",
    str: "NS-2026-101-LOISA",
    education: "STIKES Bali",
    certifications: ["BTCLS", "Emergency Nursing"],
    experience: "5+ Years",
    bio: "Highly skilled nurse specializing in IV therapy and Bali Belly recovery.",
    socials: { instagram: "#", linkedin: "#" },
  },
  {
    id: "chintya",
    type: "nurse",
    name: "Ni Putu Chintya Regina Asak",
    role: "Professional Nurse",
    image: "/images/user.jpeg",
    str: "NS-2026-102-CHIN",
    education: "Universitas Udayana",
    certifications: ["Home Care Specialist"],
    experience: "4+ Years",
    bio: "Expert in nursing care and clinical assistance for post-surgery patients.",
    socials: { instagram: "#", linkedin: "#" },
  },
  {
    id: "dimas",
    type: "nurse",
    name: "Dimas Catur Nugroho",
    role: "Professional Nurse",
    image: "/images/user.jpeg",
    str: "NS-2026-103-DIMAS",
    education: "Poltekkes Denpasar",
    certifications: ["Emergency First Aid"],
    experience: "3+ Years",
    bio: "Fast-responding nurse with extensive experience in hotel medical call-outs.",
    socials: { instagram: "#", linkedin: "#" },
  },
  {
    id: "erlita",
    type: "nurse",
    name: "Erlita Prihatin N.",
    role: "Professional Nurse",
    image: "/images/user.jpeg",
    str: "NS-2026-104-ERLIT",
    education: "STIKES Bina Husada",
    certifications: ["Pediatric Nursing"],
    experience: "4+ Years",
    bio: "Compassionate nurse specializing in infant and child medical monitoring at home.",
    socials: { instagram: "#", linkedin: "#" },
  },
  {
    id: "ns-eka",
    type: "nurse",
    name: "Ns. Putu Eka Saputra",
    role: "Professional Nurse",
    image: "/images/user.jpeg",
    str: "NS-2026-105-EKA",
    education: "STIKES Bali",
    certifications: ["BTCLS", "ICU Nursing"],
    experience: "6+ Years",
    bio: "Critical care specialist providing high-level monitoring for complex home cases.",
    socials: { instagram: "#", linkedin: "#" },
  },
  {
    id: "ns-darma",
    type: "nurse",
    name: "Ns. Gede Darmawan",
    role: "Professional Nurse",
    image: "/images/user.jpeg",
    str: "NS-2026-106-DARMA",
    education: "Universitas Udayana",
    certifications: ["Wound Care Certified"],
    experience: "5+ Years",
    bio: "Specialist in advanced wound dressing and post-operative recovery care.",
    socials: { instagram: "#", linkedin: "#" },
  },
  {
    id: "ns-widya",
    type: "nurse",
    name: "Ns. Ni Kadek Widya",
    role: "Professional Nurse",
    image: "/images/user.jpeg",
    str: "NS-2026-107-WIDYA",
    education: "STIKES Bali",
    certifications: ["BTCLS", "Geriatic Care"],
    experience: "4+ Years",
    bio: "Expert in elderly care and long-term medical management for villa residents.",
    socials: { instagram: "#", linkedin: "#" },
  },
  {
    id: "ns-ari",
    type: "nurse",
    name: "Ns. I Nyoman Arianto",
    role: "Professional Nurse",
    image: "/images/user.jpeg",
    str: "NS-2026-108-ARI",
    education: "Poltekkes Denpasar",
    certifications: ["BTCLS", "Anesthesia Support"],
    experience: "5+ Years",
    bio: "Assisting in minor surgical procedures and pain management therapy.",
    socials: { instagram: "#", linkedin: "#" },
  },
  {
    id: "ns-sari",
    type: "nurse",
    name: "Ns. Ni Made Sariani",
    role: "Professional Nurse",
    image: "/images/user.jpeg",
    str: "NS-2026-109-SARI",
    education: "Universitas Udayana",
    certifications: ["BTCLS", "Maternity Care"],
    experience: "4+ Years",
    bio: "Dedicated to maternal health and newborn care assistance in villa settings.",
    socials: { instagram: "#", linkedin: "#" },
  },
  {
    id: "ns-yuda",
    type: "nurse",
    name: "Ns. Putu Yuda Pratama",
    role: "Professional Nurse",
    image: "/images/user.jpeg",
    str: "NS-2026-110-YUDA",
    education: "STIKES Bali",
    certifications: ["BTCLS", "Mental Health Nursing"],
    experience: "3+ Years",
    bio: "Providing holistic nursing care with a focus on patient psychological comfort.",
    socials: { instagram: "#", linkedin: "#" },
  },
  {
    id: "ns-mira",
    type: "nurse",
    name: "Ns. Ni Wayan Mirayanti",
    role: "Professional Nurse",
    image: "/images/user.jpeg",
    str: "NS-2026-111-MIRA",
    education: "Poltekkes Denpasar",
    certifications: ["BTCLS", "Nutrition Support"],
    experience: "4+ Years",
    bio: "Specialized in IV hydration and nutritional recovery for hangover/immunity.",
    socials: { instagram: "#", linkedin: "#" },
  },
  {
    id: "ns-bayu",
    type: "nurse",
    name: "Ns. Made Bayu Krisna",
    role: "Professional Nurse",
    image: "/images/user.jpeg",
    str: "NS-2026-112-BAYU",
    education: "STIKES Bali",
    certifications: ["BTCLS", "Emergency Trauma"],
    experience: "5+ Years",
    bio: "Experienced in trauma response and mobile medical unit coordination.",
    socials: { instagram: "#", linkedin: "#" },
  },
  {
    id: "ns-indah",
    type: "nurse",
    name: "Ns. Ni Putu Indah Permata",
    role: "Professional Nurse",
    image: "/images/user.jpeg",
    str: "NS-2026-113-INDAH",
    education: "Universitas Udayana",
    certifications: ["BTCLS", "Infection Control"],
    experience: "4+ Years",
    bio: "Focused on clinical safety and high-standard sterilization in home care.",
    socials: { instagram: "#", linkedin: "#" },
  },
  {
    id: "ns-gungde",
    type: "nurse",
    name: "Ns. Anak Agung Gede Putra",
    role: "Professional Nurse",
    image: "/images/user.jpeg",
    str: "NS-2026-114-GUNGDE",
    education: "STIKES Bali",
    certifications: ["BTCLS", "Renal Care"],
    experience: "6+ Years",
    bio: "Senior nurse with expertise in dialysis assistance and renal monitoring.",
    socials: { instagram: "#", linkedin: "#" },
  },
  {
    id: "ns-ayu",
    type: "nurse",
    name: "Ns. Kadek Ayu Lestari",
    role: "Professional Nurse",
    image: "/images/user.jpeg",
    str: "NS-2026-115-AYU",
    education: "Poltekkes Denpasar",
    certifications: ["BTCLS", "Palliative Care"],
    experience: "4+ Years",
    bio: "Specializing in compassionate palliative care and family medical support.",
    socials: { instagram: "#", linkedin: "#" },
  },
  {
    id: "ns-bagus",
    type: "nurse",
    name: "Ns. Nyoman Bagus Kurniawan",
    role: "Professional Nurse",
    image: "/images/user.jpeg",
    str: "NS-2026-116-BAGUS",
    education: "STIKES Bali",
    certifications: ["BTCLS", "General Home Care"],
    experience: "3+ Years",
    bio: "Providing versatile nursing services for general health check-ups and IV drips.",
    socials: { instagram: "#", linkedin: "#" },
  },
];
